services:
  todo-app:
    image: todo-app:v1.0.1
    ports:
      - "5000:5000"
    env_file:
      - .env
# Uncomment these two lines below if running on WSL
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#networks:
 # default:
  #  name: todo-app-network
   # ipam:
    #  config:
     #   - subnet: 172.19.0.0/16
